const util = require("util");
const debug = util.debuglog("workers");

const {
  CHECKS_NOT_FOUND_MESSAGE,
  TRUNCATING_FILE_SUCCESS_MESSAGE,
  TRUNCATING_FILE_ERROR_MESSAGE,
  NOT_COMPRESSED_FILE_MESSAGE,
  LOGGING_SUCCESS_MESSAGE,
  NOT_FOUND_LOGS_MESSAGE,
  LOGGING_FAIL_MESSAGE,
  SUCCESS_SEND_SMS_MESSAGE,
  ERROR_SEND_SMS_MESSAGE,
  NO_ALERT_NEEDED_MESSAGE,
  SAVE_UPDATE_CHECKS_ERROR_MESSAGE,
  NOT_PROPERTY_FORMATTED_MESSAGE,
} = require("./worker.constants");

class WorkerDebugger {
  CHECKS_NOT_FOUND() {
    return debug(CHECKS_NOT_FOUND_MESSAGE);
  }

  LOGGING_FAIL() {
    return debug(LOGGING_FAIL_MESSAGE);
  }

  NOT_FOUND_LOGS() {
    return debug(NOT_FOUND_LOGS_MESSAGE);
  }

  LOGGING_SUCCESS() {
    return debug(LOGGING_SUCCESS_MESSAGE);
  }

  NOT_COMPRESSED_FILE(err) {
    return debug(NOT_COMPRESSED_FILE_MESSAGE, err);
  }

  TRUNCATING_FILE_ERROR() {
    return debug(TRUNCATING_FILE_ERROR_MESSAGE);
  }

  TRUNCATING_FILE_SUCCESS() {
    return debug(TRUNCATING_FILE_SUCCESS_MESSAGE);
  }

  NOT_PROPERTY_FORMATTED() {
    return debug(NOT_PROPERTY_FORMATTED_MESSAGE);
  }
  SAVE_UPDATE_CHECKS_ERROR() {
    return debug(SAVE_UPDATE_CHECKS_ERROR_MESSAGE);
  }
  NO_ALERT_NEEDED() {
    return debug(NO_ALERT_NEEDED_MESSAGE);
  }
  ERROR_SEND_SMS(err) {
    return debug(ERROR_SEND_SMS_MESSAGE, err);
  }
  SUCCESS_SEND_SMS(msg) {
    return debug(SUCCESS_SEND_SMS_MESSAGE, msg);
  }

  ERROR_READING_CHECKS(err) {
    return debug(ERROR_SEND_SMS_MESSAGE, err);
  }
}

module.exports = new WorkerDebugger();
